### ISSUE TITLE
i think there alot error's, bugs and bad documentation about this module

### ISSUE THREAD

**Issue by ghost** [oalders/business-paypal-api#16]
i think there a lot error's, bugs and bad documentation about this module. because today one of my friends tried it. and there was a weird response.
first 500 timeout . i got it fixed by using the latest update module
now zero response with no erorr log in the file LOL. the module itself has no error handling 

use Business::PayPal::API qw(TransactionSearch);
use Data::Dumper;

print "Content-type: text/html\n\n"; 

my $pp = Business::PayPal::API->new(
  Username => 'username',
  Password => 'password',
  CertFile => 'cert_key_pem.txt',
  KeyFile  => 'cert_key_pem.txt',
  sandbox  => 0, 
  timeout => 5  
  );
 
$transid = '88TG36657A371';
 
my $transactions = $pp->TransactionSearch(
    TransactionID => $transid
);

for my $rec ( @$transactions ) {
    print "Record:\n";
    print "TransactionID: " . $rec->{TransactionID} . "\n";
    print  "Payer Email: " . $rec->{Payer} . "\n";
    print  "Amount: " . $rec->{GrossAmount} . "\n\n";
    print   "Status: " . $rec->{Status} . "\n\n";
}

**Comment by oalders** [comment]
You've shown me some code, but you haven't shown me any output. Try adding:

```perl
use LWP::ConsoleLogger::Everywhere;
```

to the top of your code and re-running it.  Does that help find the problem?

**Comment by kingn218** [comment]
500 read timeout at Business/PayPal/API.pm line 164.:
thats the error

this is the output 
$VAR1 = {};

this is the code 

use Business::PayPal::API qw(GetTransactionDetails);
use Data::Dumper;
$ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0;


my $pp = Business::PayPal::API->new(
  Username => 'username',
  Password => 'password',
  CertFile => 'cert_key_pem.txt',
  KeyFile  => 'cert_key_pem.txt',
  sandbox  => 0, 
  timeout => 5
  );
 
$trans_id  = '89G36657A37010451';


 my %response = $pp->GetTransactionDetails( TransactionID => $trans_id );
 print "Content-type: text/html\n\n"; 
 print Dumper \%response;

**Comment by oalders** [comment]
Try adding:

```perl
use LWP::ConsoleLogger::Everywhere;
```

to the top of your code and re-running it.  Does that help find the problem?
